### ISSUE TITLE
Init should check value in LocalStorage instead of clear

### ISSUE THREAD

**Issue by GrandSchtroumpf** [Hugo-Hontans/Dappsnation#1]
The function `init()` should check if there is data in localstorage: 
- If there is : get them.
- If not : use default values
https://github.com/Hugo-Hontans/Dappsnation/blob/6a33bbeec47db6a7f8e9860164a0dff5b320141b/src/app/videogame.service.ts#L12

**Comment by Hugo-Hontans** [comment]
I worked that
