### ISSUE TITLE
Use pipe Currency

### ISSUE THREAD

**Issue by GrandSchtroumpf** [Hugo-Hontans/Dappsnation#2]
Use the [pipe "currency"](https://angular.io/api/common/CurrencyPipe) from Angular instead of hard 

https://github.com/Hugo-Hontans/Dappsnation/blob/6a33bbeec47db6a7f8e9860164a0dff5b320141b/src/app/view/view.component.html#L10

**Comment by Hugo-Hontans** [comment]
Now I use the pipe "currency". Thank you
